language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - hhvm

env:
  - DB=mysql

before_script:
  - composer install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "drop database IF EXISTS danpu;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database danpu;" -uroot; fi

script:
  - ./vendor/bin/phpcs --standard=PSR1,PSR2 src tests
  - ./vendor/bin/phpunit --configuration tests/travis/phpunit.$DB.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
