language: php
php:
  - 5.5
  - 5.4
  - 5.3

env:
  - DB=mysql

before_script:
  - composer install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "drop database IF EXISTS danpu;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database danpu;" -uroot; fi

script:
  - ./vendor/bin/phpcs --standard=PSR1,PSR2 src tests
  - ./vendor/bin/phpunit --configuration tests/travis/phpunit.$DB.xml

after_script:
  - ./vendor/bin/coveralls -v
